version: "3"

services:
  node:
    image: node:16.14
    build: .
    container_name: sistema_autenticacao
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      # MYSQL_DB_NAME: sistema_autenticacao
      MYSQL_HOST: db
      JWT_SECRET: secretPassword
      API_HOST: 'node'
      API_PORT: 3000
      NODE_ENV: 'development'
    networks:
      - sistema_autenticacao_net

  #---------------------------------------------------#

  db:
    image: mysql:8.0.23
    container_name: sistema_autenticacao_db
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    networks:
      - sistema_autenticacao_net

#-----------------------------------------------------#

networks:
  sistema_autenticacao_net:
    driver: bridge
